[package]
name = "ftl_http"
version = "0.1.0"
authors = ["Mcat12 <mark@pi-hole.net>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
libc = "0.2"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1.0"
serde_derive = "1.0"
